### ISSUE TITLE
Improve the update metadata mechanism

### ISSUE THREAD

**Issue by cedvdb** [cedvdb/dart_phone_metadata#7]
Currently the update steps for updating the metadata are a bit manual as opposed to run a simple script.

the steps are described in resources/readme. A better alternative would be to make an update.sh script that's a run and done thing so it's easier for people to contribute (and for this library to stay up to date with the latest metadata).

The update.sh script would:

  - fetch lib phone number metadata.xml
  - convert the xml to json (using libphonenuber update.sh thing)
  - convert the generated json into our own json format
  - convert the json format into the dart metadata files.
  - clean garbage at the end.
  
remaining manual steps (or maybe could be automated):
  - bump pubspec.yaml version
  - add changelog line "# semver: updated metadata"
  
  The goal here is to reduce the friction as to reupdate the metadata in the future although it's arguably fine now.

**Comment by cedvdb** [comment]
@ooglek I'd like your opinion on this since it's fresh in your mind, to know if that's doable as it's been some time I've looked at it.

**Comment by ooglek** [comment]
My brain clearly worked on this while I slept! I have ideas!

I don't think you need to pull the PhoneNumberKit library at all. The update script in PhoneNumberKit is already completed when they bump versions. so you could just pull the raw `PhoneNumberMetadata.json` file as the first step.

https://raw.githubusercontent.com/marmelroy/PhoneNumberKit/master/PhoneNumberKit/Resources/PhoneNumberMetadata.json

That cuts out a few steps!

The next question is -- do you need your own JSON format? At this point it probably doesn't make sense to change the process, just asking as a challenge. :-)

Next I was thinking that I'd just write a daily cron job that would check if `PhoneNumberKit` was updated, and if so, grab the JSON, run your process, and automatically create a branch and PR.

But Since you own this Repo, you could build a workflow.

https://docs.github.com/en/actions/using-workflows/about-workflows

I haven't done it, but seems like a great use of workflows to automate this process, so long as you trust `PhoneNumberKit` !

It looks like you'd have to manually trigger the workflow, or automate the detection of a new version release of PhoneNumberKit -- https://github.com/orgs/community/discussions/26323

It'd be pretty sweet if your process was merely to "hit the big red button" in the Workflow and it would pull the file, run all the `dart` code, create the PR, run the tests, automatically merge the PR if tests pass, and push a new release to GitHub, and hopefully also to pub.dev. Automation FTW!

**Comment by ooglek** [comment]
Had another thought that I put in the PR that I'll copy here.

1. Grab the latest version of `libphonenumber` `metadata.zip` file ([link](https://github.com/google/libphonenumber/blob/v8.12.52/metadata/metadata.zip))
2. Grab the latest version of `marmelroy/PhoneNumberKit` `update.sh`
3. Generate your JSON
4. [...]
5. Profit!

**Comment by cedvdb** [comment]
That'd be sweet indeed ;P however that'd require some development time to setup.

The conversion from the other json to our own json is required currently to have the json fit the data properties so it's easier to generate. I wouldn't change that step.

Thanks for the detailed reply (which was detailed a second ago).

**Comment by cedvdb** [comment]
For the update.sh script, it's really simple. imo it can be copied
